apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployments.yaml
patches:
- path: ./patch.yaml
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/managed-by=Helm
