---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: benchmark
spec:
---
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default
  namespace: benchmark
spec:
  controlPlaneRef:
    name: basic
    namespace: istio-system
