---
{{ range $a, $b := until ($.Values.bookinfo.namespace | int) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    servicemesh: istio
    app: bookinfo
    release: prometheus-operator
  name: istio-proxies
  namespace: bookinfo-{{$b}}
spec:
  selector:
    matchLabels:
      app: bookinfo
  endpoints:
  - targetPort: 15090
    path: /stats/prometheus
---
{{end}}
---
